services:
  cadastro-api:
    build:
      context: .
      dockerfile: Dockerfile

    image: ecociente-cadastro:1.0.0

    container_name: ecociente-cadastro-api

    ports:
      - "${APP_PORT:-9090}:9090"

    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE: ${SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE:-3}
      SPRING_DATASOURCE_HIKARI_MINIMUMIDLE: ${SPRING_DATASOURCE_HIKARI_MINIMUMIDLE:-1}
      SPRING_DATASOURCE_HIKARI_CONNECTIONTIMEOUT: ${SPRING_DATASOURCE_HIKARI_CONNECTIONTIMEOUT:-10000}
      SPRING_DATASOURCE_HIKARI_IDLETIMEOUT: ${SPRING_DATASOURCE_HIKARI_IDLETIMEOUT:-60000}
      SPRING_DATASOURCE_HIKARI_MAXLIFETIME: ${SPRING_DATASOURCE_HIKARI_MAXLIFETIME:-600000}

    restart: unless-stopped