apiVersion: v1
kind: ConfigMap

metadata:
  name: cadastro-config
  namespace: ecociente

data:
  SPRING_PROFILES_ACTIVE: "default"

  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"

  SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE: "3"
  SPRING_DATASOURCE_HIKARI_MINIMUMIDLE: "1"
  SPRING_DATASOURCE_HIKARI_CONNECTIONTIMEOUT: "10000"
  SPRING_DATASOURCE_HIKARI_IDLETIMEOUT: "60000"
  SPRING_DATASOURCE_HIKARI_MAXLIFETIME: "600000"